### ISSUE TITLE
Polygon object

### ISSUE THREAD

**Issue by pauljurczak** [ajhynes7/scikit-spatial#289]
Any chance of getting a Polygon class with simple methods: polygon or point inside polygon?

**Comment by ajhynes7** [comment]
`scikit-geometry` has this feature:
https://scikit-geometry.github.io/scikit-geometry/polygon.html

I haven't tried it myself; I just found it in their documentation.

**Comment by pauljurczak** [comment]
Yes, there are other libraries with Polygon. I'm using `sympy.geometry.Polygon` at the moment, but it is very slow due to their symbolic math. I was just curious, if Polygon may be on your roadmap.

**Comment by ajhynes7** [comment]
I don't have any more plans for features to this project, I'm just maintaining it by addressing issues when people raise them. I wasn't intending this project to be for computational geometry in general, just for basic spatial computations using linear algebra. `scikit-geometry` might be faster for you because it's based on CGAL.

**Comment by pauljurczak** [comment]
Thank you. That's what I wanted to know.
