### ISSUE TITLE
Faster Line.best_fit with scipy.sparse.linalg.svds

### ISSUE THREAD

**Issue by seirios** [ajhynes7/scikit-spatial#309]
Hello!
I'm using `Line.best_fit` with some tens of thousands to a few hundred thousand points, and I've found that using `scipy.sparse.linalg.svds` instead of `np.linalg.svd` leads to faster runtimes and lower memory usage. Since only the first eigenvector is needed, computing all of them seems wasteful.
Could this be an improvement? Perhaps use `scipy` if available, otherwise fallback to `numpy`?
Cheers!

**Comment by ajhynes7** [comment]
Hi @seirios, 

Thanks for bringing this to my attention. Could you put up a PR for this? See if you can replace the numpy function with the scipy function and still get all the tests to pass.

**Comment by CristianoPizzamiglio** [comment]
Hi guys!

@seirios If you want I can take care of this PR.

Bye!

**Comment by CristianoPizzamiglio** [comment]
@seirios ...and by the way, how much is the computation speed up? Thanks!

**Comment by ajhynes7** [comment]
`scipy.sparse.linalg.svds` was only recently released in [SciPy 1.8.0](https://docs.scipy.org/doc/scipy/release.1.8.0.html), and that version of SciPy requires Python >= 3.8. I've been trying to keep `scikit-spatial` supporting Python >= 3.7.

I'm also not sure if this algorithm should be used for all fitting cases, because the docstring says its for sparse arrays.

My suggestion is to use `scipy.sparse.linalg.svds` for finding the line of best fit without `scikit-spatial`. Then you can convert that into a `Line` object afterwards.
