### ISSUE TITLE
collab with `pygal`?

### ISSUE THREAD

**Issue by wolfv** [ajhynes7/scikit-spatial#59]
Hi @ajhynes7 

I just came across this repository. I have been working on a package called `pygal` which wraps a bunch of the algorithms available in CGAL.
I was also thinking of making a `scikit` style package out of it -- then i discovered yours.

Maybe there is some way to get a collaboration going?
I am not sure what that would look like though. One difficulty is that CGAL likes to use a multi-precision number type which doesn't necessarily map directly to a double ... 

Here is the package: https://github.com/wolfv/pygal

Cheers

**Comment by ajhynes7** [comment]
Hi @wolfv 
I'm glad you liked this project!

I'm not sure if combining our two packages is a good idea, because this one is meant to be based mostly on NumPy and Matplotlib. I don't know much about C++ or how to wrap it with Python.

I like your idea though to make a scikit -- maybe it could be called scikit-cgal? I noticed that there's [another package named pygal](http://pygal.org/en/stable/) for plotting, so that name could cause some confusion.

Then a user could use scikit-spatial for manipulating objects in a way familiar to NumPy, and call scikit-cgal for some more advanced geometry algorithms.
